steps:
- name: 'gcr.io/support-tools-299121/graalvm-builder'
  id: build:mvn
  args: ['./mvnw', 'package', '-Pnative']
- name: 'gcr.io/cloud-builders/docker'
  id: build:docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/slide4vr-updatestatus', '-f', 'src/main/docker/Dockerfile.native', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: ship:push
  args: ['push', 'gcr.io/$PROJECT_ID/slide4vr-updatestatus']
- name: 'gcr.io/cloud-builders/gcloud'
  id: ship:deploy
  args: ['run', 'deploy', 'slide4vr-updatestatus', '--image', 'gcr.io/$PROJECT_ID/slide4vr-updatestatus', '--region', 'us-central1', '--platform', 'managed']
options:
  machineType: 'E2_HIGHCPU_8'
images:
- gcr.io/$PROJECT_ID/slide4vr-updatestatus